# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=128)),
                ('no_of_modules', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseMapping',
            fields=[
                ('course_mapping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSpecialization',
            fields=[
                ('course_specialization_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_specialization', models.CharField(max_length=128)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='InterestSector',
            fields=[
                ('interest_sector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('personal_interest_sector', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('job_url', models.TextField(null=True)),
                ('job_position', models.TextField(null=True)),
                ('job_company', models.TextField(null=True)),
                ('job_category', models.TextField(null=True)),
                ('job_description', models.TextField(null=True)),
                ('job_date', models.DateField()),
                ('job_keyword', models.CharField(max_length=255, null=True)),
                ('job_interest', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('job_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_category', models.CharField(max_length=200)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('mbti_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('mbti_description', models.TextField()),
                ('possible_job_sector', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.IntegerField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=128)),
                ('has_prerequiste', models.BooleanField(default=True)),
                ('is_elective', models.BooleanField(default=True)),
                ('specialisation', models.CharField(max_length=128)),
                ('mod_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModuleCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Module')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq', to='app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInterestSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_interest_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InterestSector')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserElective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.User')),
                ('profile_picture', models.FileField(null=True, upload_to='')),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.User')),
                ('name', models.CharField(max_length=128)),
                ('course_specialization', models.CharField(max_length=128, null=True)),
                ('current_year', models.IntegerField()),
                ('current_semester', models.IntegerField()),
                ('email', models.CharField(max_length=128)),
                ('profile_picture', models.FileField(null=True, upload_to='')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
                ('mbti_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mbti')),
            ],
        ),
        migrations.AddField(
            model_name='userelective',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='studentinterestsector',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='coursemapping',
            name='module_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='userelective',
            unique_together=set([('module_code', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together=set([('module_code', 'prereq')]),
        ),
        migrations.AddField(
            model_name='modulecompleted',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='modulecompleted',
            unique_together=set([('module_code', 'user_id')]),
        ),
    ]
